//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorization
    {
        public int AutorizationID { get; set; }
        public Nullable<int> RuleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Rules Rules { get; set; }
    }
}
